bedtools: "bedtools/2.30.0"
bedops: "bedops/2.4.41"
cutadapt: "cutadapt/4.0"
fastqc: "fastqc/0.11.9"
fastq_screen: "fastq_screen/0.15.2"
fastxtoolkit: "fastxtoolkit/0.0.14"
multiqc: "multiqc/1.14"
perl: "perl/5.34"
picard: "picard/2.27.3"
python3: "python/3.9"
R: "R/4.2.2"
ucsc: "ucsc/445"
fastq_val: "/data/CCBR_Pipeliner/bin/fastQValidator"
juicer: "juicer/1.6"